ext_dict = {
                            'Z':".Z compressed file",
                            'zip':".zip compressed file",
                            'names':"Attribute information",
                            'data':"Tabular data file",
                            'doc':"Text document",
                            'test':"Tabular data for test",
                            'info':"Dataset information",
                            'cc':"C++ source code",
                            'data-original':"Tabular data file",
                            'version1':"Tabular data file",
                            'version2':"Tabular data file",
                            'l':"Unknown",
                            'lisp':"Lisp file",
                            'assumable':"Unknown",
                            'tag':"Attribute information",
                            'mod':"Unknown",
                            'original':"Tabular data",
                            'DOCUMENTATION':"Text file",
                            'c':"C source code",
                            'txt':"Text file",
                            'gz':"TAR compressed file",
                            'theory':"Unknown",
                            'train':"Training data file",
                            'dat':"Tabular data",
                            'tar':"TAR compressed file",
                            'tes':"Test data file",
                            'tra':"Training data file",
                            'html':"HTML source code",
                            'bz2':"TAR compressed file",
                            'pl':"PERL script",
                            'supplement':"Unknown",
                            'sql':"SQL script",
                            'jpg':"JPG image file",
                            'gif':"GIF file",
                            'col':"Unknown",
                            'ps':"Postscript file",
                            'tex':"LATEX file",
                            'old':"Unknown",
                            'jpeg':"JPG image file",
                            'data-numeric':"Tabular data",
                            'trn':"Training data file",
                            'tst':"Test data file",
                            'list':"Tabular data file",
                            'all-data':"Tabular data file",
                            'mines':"Unknown",
                            'rocks':"Unknown",
                            'tr-orig-order':"Tabular data file",
                            'events':"Unknown",
                            'data1':"Tabular data file",
                            'data2':"Tabular data file",
                            'pdf':"PDF file",
                            'noos':"Unknown",
                            'csv':"CSV data file",
                            'labels':"Attribute information file",
                            'text':"Text file",
                            'htm':"HTML source code",
                            'png':"PNG image file",
                            'xls':"XLS file",
                            'arff':"Unknown",
                            'xlsx':'XLS file',
                            '7z':"7z compressed file"
                            }
