# Generated by Django 2.0.6 on 2018-06-14 23:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('no_instances', models.IntegerField(default=None, null=True)),
                ('no_attr', models.IntegerField(default=None, null=True)),
                ('url', models.URLField(unique=True)),
                ('download_url', models.URLField(null=True)),
                ('publication_date', models.DateTimeField(null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None)),
                ('categories', models.ManyToManyField(blank=True, to='DataHiveApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_source', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('attributes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DataHiveApp.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='RepoMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DATAVERSE', 'Harvard Dataverse'), ('UCI', 'UCI - Machine Learning Repository')], default='DATAVERSE', max_length=10, unique=True)),
                ('last_fetch_page', models.IntegerField(blank=True, default=0, null=True)),
                ('last_fetch_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataHiveApp.DataSet')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datasets', to='DataHiveApp.RepoMetadata'),
        ),
    ]
